version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    BUILD_FOLDER: "dist/amcart-E-Commerce"
phases:
  install:
    commands:
      - echo "Installing source NPM dependencies…"
      - npm install
      - npm install -g @angular/cli
      #- curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      #- sudo apt-get install -y nodejs
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Checking environment variables..."
      - env  # This prints all available environment variables in the logs
      - export MY_SECRET=$(aws secretsmanager get-secret-value --secret-id ecom-frontend-M8e7sz --query SecretString --output text)
  build:
    commands:
      - echo Build started on `date`
      - ng run amcart-E-Commerce:collect-vars
      - ng build
  post_build:
    commands:
      - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --cache-control max-age=${CACHE_CONTROL}
      - echo Build completed on `date`
      - echo 'Invalidating distribuition cache'
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
